<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="airlines.xsl"?>

<!--Inline DTD-->
<!DOCTYPE airlines
[
    <!ELEMENT airlines (airline+)>
    <!ELEMENT airline (id,name,street?,city,region,country,parks,routes)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT street (#PCDATA)>
    <!ELEMENT region (#PCDATA)>
    <!ELEMENT parks (park+)>
    <!ELEMENT park (parking_id,manufacturer,routeType,year)>
    <!ELEMENT parking_id (#PCDATA)>
    <!ELEMENT manufacturer (#PCDATA)>
    <!ELEMENT routeType (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT routes (route+)>
    <!ELEMENT route (vehicle,departure,destination)>
    <!ELEMENT vehicle (#PCDATA)>
    <!ELEMENT departure (dep_airport,dep_city,dep_region?,dep_country)>
    <!ELEMENT dep_airport (#PCDATA)>
    <!ELEMENT dep_city (#PCDATA)>
    <!ELEMENT dep_region (#PCDATA)>
    <!ELEMENT dep_country (#PCDATA)>
    <!ELEMENT destination (dest_airport?,dest_city?,dest_region?,dest_country?)>
    <!ELEMENT dest_airport (#PCDATA)>
    <!ELEMENT dest_city (#PCDATA)>
    <!ELEMENT dest_country (#PCDATA)>
    <!ELEMENT dest_region (#PCDATA)>
]>


<airlines>
    <airline>
        <id>88ef283c-b44f-43f7-81e7-2c3e1266e2fe</id>
        <name>Hickle and Sons</name>
        <street>506 8th Court</street>
        <city>Providence</city>
        <region>Rhode Island</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>d1e1a67f-5e62-4495-957f-3b7c38613928</parking_id>
                <manufacturer>Mann Inc</manufacturer>
                <routeType>short-distance</routeType>
                <year>2018</year>
            </park>
            <park>
                <parking_id>0e194364-fb2d-469c-8be1-e4a1a02ce7b2</parking_id>
                <manufacturer>Moen LLC</manufacturer>
                <routeType>short-distance</routeType>
                <year>2015</year>
            </park>
            <park>
                <parking_id>42650abf-eab0-44e0-8995-031545685a91</parking_id>
                <manufacturer>Sipes, Rohan and Jerde</manufacturer>
                <routeType>local</routeType>
                <year>1987</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>cf462119-4c9f-4d21-ab9f-80f33605f378</vehicle>
                <departure>
                    <dep_airport>Balistreri-Pagac</dep_airport>
                    <dep_city>Gostivar</dep_city>
                    <dep_country>Macedonia</dep_country>
                </departure>
                <destination>
                    <dest_airport>Treutel Inc</dest_airport>
                    <dest_city>Vandœuvre-lès-Nancy</dest_city>
                    <dest_region>Lorraine</dest_region>
                    <dest_country>France</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>2579d016-e051-474f-994f-9ecb96543ca9</vehicle>
                <departure>
                    <dep_airport>Buckridge LLC</dep_airport>
                    <dep_city>Ta'erqi</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Heller Inc</dest_airport>
                    <dest_city>Jeziorany</dest_city>
                    <dest_country>Poland</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>e72ee5a9-3bb6-4b60-b083-73cf88ed38e0</id>
        <name>Marks-Schaefer</name>
        <street>453 Bayside Parkway</street>
        <city>Lumby</city>
        <region>British Columbia</region>
        <country>Canada</country>
        <parks>
            <park>
                <parking_id>c330c3a5-4dab-4eba-8857-ce45ce824109</parking_id>
                <manufacturer>Walter LLC</manufacturer>
                <routeType>local</routeType>
                <year>2006</year>
            </park>
            <park>
                <parking_id>6ce3ac85-069c-4a53-a584-cd9eac454a6c</parking_id>
                <manufacturer>Becker Group</manufacturer>
                <routeType>long-distance</routeType>
                <year>2003</year>
            </park>
            <park>
                <parking_id>b43469a5-d188-47dd-8335-5105083131cc</parking_id>
                <manufacturer>Willms-Thiel</manufacturer>
                <routeType>short-distance</routeType>
                <year>1990</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>ea970d79-3ae5-42f0-81e0-c262985f63db</vehicle>
                <departure>
                    <dep_airport>Bayer-Mante</dep_airport>
                    <dep_city>Abelheira</dep_city>
                    <dep_region>Porto</dep_region>
                    <dep_country>Portugal</dep_country>
                </departure>
                <destination>
                    <dest_airport>Beer-Bayer</dest_airport>
                    <dest_city>Tak Bai</dest_city>
                    <dest_country>Thailand</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>28c746c4-7cd5-469e-8cf9-36fb04efa2d0</vehicle>
                <departure>
                    <dep_airport>Lubowitz, Pagac and Christiansen</dep_airport>
                    <dep_city>Malunda</dep_city>
                    <dep_country>Indonesia</dep_country>
                </departure>
                <destination>
                    <dest_airport>Mohr-Bernhard</dest_airport>
                    <dest_city>Nambalan</dest_city>
                    <dest_country>Philippines</dest_country>
                </destination>
            </route>
        </routes>        
    </airline>
    <airline>
        <id>d3890c4a-9318-4f43-96e5-c1dab32d6197</id>
        <name>Olson Group</name>
        <street>61 Buena Vista Avenue</street>        
        <city>Cincinnati</city>
        <region>Ohio</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>b9cbd5f7-d0c7-4210-b8a9-92ab6ef86e39</parking_id>
                <manufacturer>Hahn, Rosenbaum and Renner</manufacturer>
                <routeType>long-distance</routeType>
                <year>2000</year>
            </park>
            <park>
                <parking_id>6ac12781-b269-45d9-b3f7-ffd6f054b849</parking_id>
                <manufacturer>O'Reilly Inc</manufacturer>
                <routeType>local</routeType>
                <year>2005</year>
            </park>
            <park>
                <parking_id>c451a7d7-540a-42fb-b872-5026a49a6337</parking_id>
                <manufacturer>Conn-Nolan</manufacturer>
                <routeType>short-distance</routeType>
                <year>2002</year>
            </park>
        </parks>        
        <routes>
            <route>
                <vehicle>f9d6cfe6-8294-44cb-b182-bd8c54943bd5</vehicle>
                <departure>
                    <dep_airport>Wilkinson-Nikolaus</dep_airport>
                    <dep_city>Yanmen</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Reichert, Roob and Balistreri</dest_airport>
                    <dest_city>Santa</dest_city>
                    <dest_country>Peru</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>a448d3ae-8734-49df-ab2a-170fffc4c610</vehicle>
                <departure>
                    <dep_airport>Barrows-Schmeler</dep_airport>
                    <dep_city>Vänersborg</dep_city>
                    <dep_region>Västra Götaland</dep_region>
                    <dep_country>Sweden</dep_country>
                </departure>
                <destination>
                    <dest_airport>Jerde-Anderson</dest_airport>
                    <dest_city>Akure</dest_city>
                    <dest_country>Nigeria</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>a6739349-84ed-41ad-97cb-a35be66f55a1</id>
        <name>Leannon-Bins</name>
        <street>2263 Huxley Court</street>
        <city>El Paso</city>
        <region>Texas</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>af31030c-07e8-403c-a3fd-6817d82bae45</parking_id>
                <manufacturer>Shanahan-Hoppe</manufacturer>
                <routeType>local</routeType>
                <year>2009</year>
            </park>
            <park>
                <parking_id>7c80a342-558a-4438-84eb-32978446cbc7</parking_id>
                <manufacturer>Rath Inc</manufacturer>
                <routeType>local</routeType>
                <year>1996</year>
            </park>
            <park>
                <parking_id>7a407ce1-a99d-4766-bb60-97c5c2b13836</parking_id>
                <manufacturer>Graham, Pacocha and Pollich</manufacturer>
                <routeType>long-distance</routeType>
                <year>1986</year>
            </park>
        </parks>        
        <routes>
            <route>
                <vehicle>678b337e-4570-4c1f-bd05-be05fecd45d9</vehicle>
                <departure>
                    <dep_airport>Krajcik and Sons</dep_airport>
                    <dep_city>Unión</dep_city>
                    <dep_country>Argentina</dep_country>
                </departure>
                <destination>
                    <dest_airport>Collins-Kris</dest_airport>
                    <dest_city>Višnjevac</dest_city>
                    <dest_country>Croatia</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>a66e8f1c-4d4c-45b0-8ce8-176c97d80c5e</vehicle>
                <departure>
                    <dep_airport>McGlynn LLC</dep_airport>
                    <dep_city>Gaozhai</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Reilly-Ortiz</dest_airport>
                    <dest_city>Fermelã</dest_city>
                    <dest_region>Aveiro</dest_region>
                    <dest_country>Portugal</dest_country>
                </destination>
            </route>
        </routes>        
    </airline>
    <airline>
        <id>dbd64922-58e4-4a0f-8769-4c685ef131b4</id>
        <name>Toy-Balistreri</name>
        <street>99317 Lukken Court</street>           
        <city>Los Angeles</city>
        <region>California</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>204e8e29-c432-4501-9bd1-81c20f06725f</parking_id>
                <manufacturer>Jacobi, Willms and Predovic</manufacturer>
                <routeType>long-distance</routeType>
                <year>2018</year>
            </park>
            <park>
                <parking_id>a78f1424-f95d-4af1-ac5e-45a10df18e4d</parking_id>
                <manufacturer>Grady, Davis and Nitzsche</manufacturer>
                <routeType>long-distance</routeType>
                <year>2014</year>
            </park>
            <park>
                <parking_id>61d7b949-58b9-4ae0-860d-c2e544d20914</parking_id>
                <manufacturer>Bayer LLC</manufacturer>
                <routeType>local</routeType>
                <year>1991</year>
            </park>
        </parks>        
        <routes>
            <route>
                <vehicle>b9aaf947-c234-4f21-961d-88d20b4a0079</vehicle>
                <departure>
                    <dep_airport>Spinka-Rodriguez</dep_airport>
                    <dep_city>Fenhe</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Goldner, Harris and Stroman</dest_airport>
                    <dest_city>Dalheim</dest_city>
                    <dest_country>Luxembourg</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>98d1ca66-0591-4896-892e-d406a49c1fa8</vehicle>
                <departure>
                    <dep_airport>Considine LLC</dep_airport>
                    <dep_city>Moss</dep_city>
                    <dep_region>Ostfold</dep_region>
                    <dep_country>Norway</dep_country>
                </departure>
                <destination>
                    <dest_airport>Dicki-Hermann</dest_airport>
                    <dest_city>Ōtsuki</dest_city>
                    <dest_country>Japan</dest_country>
                </destination>
            </route>
        </routes>        
    </airline>
    <airline>
        <id>06013463-e5af-4ea5-a64a-2f2eb95c8726</id>
        <name>Koss, Harvey and DuBuque</name>
        <street>24118 Bowman Park</street>
        <city>Glasgow</city>
        <region>Scotland</region>
        <country>United Kingdom</country>
        <parks>
            <park>
                <parking_id>f8d32364-c5a9-4e2b-86f0-e0d0eac4189a</parking_id>
                <manufacturer>Bashirian LLC</manufacturer>
                <routeType>long-distance</routeType>
                <year>1986</year>
            </park>
            <park>
                <parking_id>4e6cf1ff-1f14-412b-bb61-e45a26c8c130</parking_id>
                <manufacturer>Little-Feil</manufacturer>
                <routeType>long-distance</routeType>
                <year>2020</year>
            </park>
            <park>
                <parking_id>7c568456-6908-4359-8040-d1dc9ac71145</parking_id>
                <manufacturer>Muller, Goldner and Crist</manufacturer>
                <routeType>local</routeType>
                <year>1983</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>f3bc020b-53c4-4e6b-828b-8be3c5778bb2</vehicle>
                <departure>
                    <dep_airport>Fadel Inc</dep_airport>
                    <dep_city>Casal da Anja</dep_city>
                    <dep_region>Leiria</dep_region>
                    <dep_country>Portugal</dep_country>
                </departure>
                <destination>
                    <dest_airport>Mueller-Johnston</dest_airport>
                    <dest_city>Mogok</dest_city>
                    <dest_country>Myanmar</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>50c79a57-3afb-47a2-869a-5419fa5dbb3d</vehicle>
                <departure>
                    <dep_airport>Lind-Dibbert</dep_airport>
                    <dep_city>Baoluan</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Grant Inc</dest_airport>
                    <dest_city>Palhoça</dest_city>
                    <dest_country>Brazil</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>48e509a3-f2a2-494b-a11c-66de0cfe67f9</id>
        <name>Schaden-Konopelski</name>
        <street>0 Donald Lane</street>
        <city>Tulsa</city>
        <region>Oklahoma</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>65d818af-d2da-4475-8f1c-dee3f3364e9b</parking_id>
                <manufacturer>Bernier-Beer</manufacturer>
                <routeType>local</routeType>
                <year>2001</year>
            </park>
            <park>
                <parking_id>90c86de3-1f90-439a-a62a-06f2d80d3360</parking_id>
                <manufacturer>Ortiz-Nicolas</manufacturer>
                <routeType>short-distance</routeType>
                <year>1986</year>
            </park>
            <park>
                <parking_id>ffbb2e3f-1305-4737-8760-8582fd3b5d52</parking_id>
                <manufacturer>Hoeger-Kling</manufacturer>
                <routeType>long-distance</routeType>
                <year>1983</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>856e3a7e-6701-4efa-a412-204aaa36d645</vehicle>
                <departure>
                    <dep_airport>Rath, Rempel and Green</dep_airport>
                    <dep_city>Jiuquan</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Streich LLC</dest_airport>
                    <dest_city>Thai Charoen</dest_city>
                    <dest_country>Thailand</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>20227701-eb37-438e-a1db-bb94fbfa04d6</vehicle>
                <departure>
                    <dep_airport>Cruickshank and Sons</dep_airport>
                    <dep_city>Xingbin</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Lebsack, Turner and Reilly</dest_airport>
                    <dest_city>Karagay</dest_city>
                    <dest_country>Russia</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>283fd4e1-ec3c-4445-9150-8ad5067a84bc</id>
        <name>Olson-MacGyver</name>
        <street>9412 Muir Court</street>
        <city>Miami</city>
        <region>Florida</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>3a0b3f62-d8ff-4e55-9524-c1149633ccaf</parking_id>
                <manufacturer>Waelchi Inc</manufacturer>
                <routeType>local</routeType>
                <year>1987</year>
            </park>
            <park>
                <parking_id>6bb84f8c-b31d-44a8-87c1-a55c69953529</parking_id>
                <manufacturer>Aufderhar and Sons</manufacturer>
                <routeType>short-distance</routeType>
                <year>2013</year>
            </park>
            <park>
                <parking_id>557e1e1b-08fe-447f-9bf6-5516f9081ccb</parking_id>
                <manufacturer>Hand Inc</manufacturer>
                <routeType>short-distance</routeType>
                <year>1985</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>64540c86-309a-4f8c-8111-a14bb8771623</vehicle>
                <departure>
                    <dep_airport>Stanton, Sanford and Wilderman</dep_airport>
                    <dep_city>Aguilares</dep_city>
                    <dep_country>Argentina</dep_country>
                </departure>
                <destination>
                    <dest_airport>Waters-Koelpin</dest_airport>
                    <dest_city>Wang Chan</dest_city>
                    <dest_country>Thailand</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>5317fe82-a0e7-431d-a243-a473b5a84cbf</vehicle>
                <departure>
                    <dep_airport>Bogisich LLC</dep_airport>
                    <dep_city>Hongguang</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Koelpin and Sons</dest_airport>
                    <dest_city>Sumberkemuning</dest_city>
                    <dest_country>Indonesia</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>ac9ed5a9-ba8d-4415-b927-d3a66a529351</id>
        <name>Durgan-Armstrong</name>
        <street>31566 Darwin Center</street>
        <city>Milton</city>
        <region>Ontario</region>
        <country>Canada</country>
        <parks>
            <park>
                <parking_id>6e7984be-44c2-46b9-b7cb-86bc0b57928e</parking_id>
                <manufacturer>O'Conner, Kunde and Runte</manufacturer>
                <routeType>short-distance</routeType>
                <year>2015</year>
            </park>
            <park>
                <parking_id>56644278-2597-4014-8852-ff708af78f5f</parking_id>
                <manufacturer>Volkman and Sons</manufacturer>
                <routeType>short-distance</routeType>
                <year>1987</year>
            </park>
            <park>
                <parking_id>672cd508-19eb-42c5-aa68-51fd78305b49</parking_id>
                <manufacturer>Barton-Ondricka</manufacturer>
                <routeType>long-distance</routeType>
                <year>2003</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>767ec0b2-030b-479f-988b-2aea21ed0478</vehicle>
                <departure>
                    <dep_airport>Hessel, Schmeler and Gislason</dep_airport>
                    <dep_city>Dalam</dep_city>
                    <dep_country>Indonesia</dep_country>
                </departure>
                <destination>
                    <dest_airport>Hilpert, Emmerich and Yost</dest_airport>
                    <dest_city>Porkhov</dest_city>
                    <dest_country>Russia</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>3cceb6b4-c30b-4884-b606-4e81efd0f407</vehicle>
                <departure>
                    <dep_airport>Dooley-Schroeder</dep_airport>
                    <dep_city>Březová</dep_city>
                    <dep_country>Czech Republic</dep_country>
                </departure>
                <destination>
                    <dest_airport>Hartmann Group</dest_airport>
                    <dest_city>Abade de Vermoim</dest_city>
                    <dest_region>Braga</dest_region>
                    <dest_country>Portugal</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>8568afe4-36c0-46f0-a97a-2d26834e4729</id>
        <name>Lakin-Reynolds</name>
        <street>340 2nd Crossing</street>
        <city>Charleston</city>
        <region>West Virginia</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>beb2404e-8c3a-42ed-a902-e6fcfcaf20d3</parking_id>
                <manufacturer>Turner Inc</manufacturer>
                <routeType>short-distance</routeType>
                <year>2019</year>
            </park>
            <park>
                <parking_id>55b85e6f-472d-4e0a-a045-af862d963a88</parking_id>
                <manufacturer>Monahan LLC</manufacturer>
                <routeType>long-distance</routeType>
                <year>2008</year>
            </park>
            <park>
                <parking_id>2b54361a-0b9b-41a2-bc3b-f7ce1554d082</parking_id>
                <manufacturer>Weimann-Lockman</manufacturer>
                <routeType>local</routeType>
                <year>2017</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>17a5793c-8541-4fce-8259-025cd9667a30</vehicle>
                <departure>
                    <dep_airport>Harber, McKenzie and Prohaska</dep_airport>
                    <dep_city>Karang Tengah</dep_city>
                    <dep_country>Indonesia</dep_country>
                </departure>
                <destination>
                    <dest_airport>Weber Group</dest_airport>
                    <dest_city>Zhangdiyingzi</dest_city>
                    <dest_country>China</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>693a7e27-c56d-415a-981f-d04a6b4315e5</vehicle>
                <departure>
                    <dep_airport>Russel and Sons</dep_airport>
                    <dep_city>Zhongzuiling</dep_city>
                    <dep_country>China</dep_country>
                </departure>
                <destination>
                    <dest_airport>Streich-Wiza</dest_airport>
                    <dest_city>Sucun</dest_city>
                    <dest_country>China</dest_country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>f41f108c-6dbb-4006-b074-76bcc951f1c9</id>
        <name>Greenfelder Group</name>
        <street>93931 Stoughton Place</street>
        <city>Charleston</city>
        <region>West Virginia</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>f3fb700c-4723-46b7-813b-09af1785eeb2</parking_id>
                <manufacturer>Kunze-Medhurst</manufacturer>
                <routeType>local</routeType>
                <year>1993</year>
            </park>
            <park>
                <parking_id>b6a9331d-08b5-46b0-a6e3-d25e320782ca</parking_id>
                <manufacturer>Larson Inc</manufacturer>
                <routeType>short-distance</routeType>
                <year>1989</year>
            </park>
            <park>
                <parking_id>918c3c1c-e76b-471c-8853-676ba796f9f3</parking_id>
                <manufacturer>Nader, Schuppe and Walsh</manufacturer>
                <routeType>local</routeType>
                <year>2009</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>d4a19bbe-7f13-443e-9572-945981f5e0ea</vehicle>
                <departure>
                    <dep_airport>Kuhn and Sons</dep_airport>
                    <dep_city>Yeshan</dep_city>
                    <dep_country>China</dep_country>
                </departure>            
                <destination>
                    <dest_airport>Daugherty, Ratke and Sanford</dest_airport>
                    <dest_city>Miura</dest_city>
                    <dest_country>Japan</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>9319ae34-cf6d-4da0-9bf2-f481878d6d42</vehicle>
                <departure>
                    <dep_airport>Thompson, Romaguera and Johnston</dep_airport>
                    <dep_city>Buenavista</dep_city>
                    <dep_country>Colombia</dep_country>
                </departure>
                <destination>
                    <dest_airport>Jones Group</dest_airport>
                    <dest_city>Hebei</dest_city>
                    <dest_country>China</dest_country>
                </destination>
            </route>
        </routes>
       
    </airline>
    <airline>
        <id>12675df3-9deb-4232-a377-cb67366a814e</id>
        <name>Smith, Kris and Mohr</name>
        <street>93095 5th Park</street>
        <city>Memphis</city>
        <region>Tennessee</region>
        <country>United States</country>
        <parks>
            <park>
                <parking_id>02144c49-1d0d-42a7-ada1-c05516696247</parking_id>
                <manufacturer>Feil-Rowe</manufacturer>
                <routeType>short-distance</routeType>
                <year>2010</year>
            </park>
            <park>
                <parking_id>fa7f75a6-524a-4719-9e16-53e501a0fb7c</parking_id>
                <manufacturer>Romaguera-Bahringer</manufacturer>
                <routeType>long-distance</routeType>
                <year>2020</year>
            </park>
            <park>
                <parking_id>551aacfc-02c2-4ea4-875a-91e5a6ad2cd9</parking_id>
                <manufacturer>Murphy Inc</manufacturer>
                <routeType>short-distance</routeType>
                <year>2015</year>
            </park>
        </parks>        
        <routes>
            <route>
                <vehicle>233aaad2-9129-4c2f-9723-833b57bc62a2</vehicle>
                <departure>
                    <dep_airport>Bashirian, Pfeffer and Hettinger</dep_airport>
                    <dep_city>Bardo</dep_city>
                    <dep_country>Poland</dep_country>
                </departure>
                <destination>
                    <dest_airport>Dickinson-Pacocha</dest_airport>
                    <dest_city>Malanday</dest_city>
                    <dest_country>Philippines</dest_country>
                </destination>
            </route>
            <route>
                <vehicle>d94b119c-cddb-4a8c-af76-8e25cca3e3b7</vehicle>
                <departure>
                    <dep_airport>Abshire-Schowalter</dep_airport>
                    <dep_city>General Conesa</dep_city>
                    <dep_country>Argentina</dep_country>
                </departure>
                <destination>
                    <dest_airport>Ward, King and Koepp</dest_airport>
                    <dest_city>Bergen</dest_city>
                    <dest_region>Hordaland</dest_region>
                    <dest_country>Norway</dest_country>
                </destination>
            </route>
        </routes>       
    </airline>
    <airline>
        <id>af4ac783-28f3-4a5c-8650-a81bde9329d4</id>
        <name>Dickens Inc</name>
        <street>2 Gale Street</street>
        <city>Berthierville</city>
        <region>Québec</region>
        <country>Canada</country>
        <parks>
            <park>
                <parking_id>d2a67551-66b1-4dfb-b706-a8796fbdac73</parking_id>
                <manufacturer>Bashirian, Johnston and Botsford</manufacturer>
                <routeType>short-distance</routeType>
                <year>2015</year>
            </park>
            <park>
                <parking_id>fdaee798-c526-4a44-b800-fe95f948e716</parking_id>
                <manufacturer>Bernhard Group</manufacturer>
                <routeType>short-distance</routeType>
                <year>2019</year>
            </park>
            <park>