<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="clinic.xsl"?>
<!DOCTYPE clinics 
[
<!ELEMENT clinics (clinic)+>
<!ATTLIST clinics
    xmlns CDATA #FIXED ''>

<!ELEMENT clinic (address,employee+,drug+)>
<!ATTLIST clinic
    xmlns CDATA #FIXED ''
    id CDATA #REQUIRED>

<!ELEMENT address (street,city,region,country)>
<!ATTLIST address
    xmlns CDATA #FIXED ''>

<!ELEMENT employee (firstName,lastName,empType)>
<!ATTLIST employee
    xmlns CDATA #FIXED ''
    id CDATA #REQUIRED>

<!ELEMENT drug (manufacturer,brand,name,diagnosisCode,diagnosisDescription,qty)>
<!ATTLIST drug
    xmlns CDATA #FIXED ''
    code NMTOKEN #REQUIRED>

<!ELEMENT street (#PCDATA)>
<!ATTLIST street
    xmlns CDATA #FIXED ''>

<!ELEMENT city (#PCDATA)>
<!ATTLIST city
    xmlns CDATA #FIXED ''>

<!ELEMENT region (#PCDATA)>
<!ATTLIST region
    xmlns CDATA #FIXED ''>

<!ELEMENT country (#PCDATA)>
<!ATTLIST country
    xmlns CDATA #FIXED ''>

<!ELEMENT firstName (#PCDATA)>
<!ATTLIST firstName
    xmlns CDATA #FIXED ''>

<!ELEMENT lastName (#PCDATA)>
<!ATTLIST lastName
    xmlns CDATA #FIXED ''>

<!ELEMENT empType (#PCDATA)>
<!ATTLIST empType
    xmlns CDATA #FIXED ''>

<!ELEMENT manufacturer (#PCDATA)>
<!ATTLIST manufacturer
    xmlns CDATA #FIXED ''>

<!ELEMENT brand (#PCDATA)>
<!ATTLIST brand
    xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    xmlns CDATA #FIXED ''>

<!ELEMENT diagnosisCode (#PCDATA)>
<!ATTLIST diagnosisCode
    xmlns CDATA #FIXED ''>

<!ELEMENT diagnosisDescription (#PCDATA)>
<!ATTLIST diagnosisDescription
    xmlns CDATA #FIXED ''>

<!ELEMENT qty (#PCDATA)>
<!ATTLIST qty
    xmlns CDATA #FIXED ''>
]>
<clinics>
  <clinic id="ce2d33d3-342c-4d55-9c8f-e5b35535941c">
    <address>
        <street>4 Ridge Oak Plaza</street>
        <city>Tampa</city>
        <region>Florida</region>
        <country>United States</country>
    </address>
    <employee id="d4cc0867-340d-4649-88f4-51c97f26432b">
        <firstName>Zorine</firstName>
        <lastName>Climson</lastName>
        <empType>contractor</empType>
    </employee>
    <employee id="b248a336-cf55-48e1-8c19-bdff3ebec577">
        <firstName>Gerhard</firstName>
        <lastName>O'Dyvoy</lastName>
        <empType>full-time</empType>
    </employee>
    <employee id="d7a03a4c-db45-4d84-b25a-9e7cbccc603f">
        <firstName>Titus</firstName>
        <lastName>Sivess</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="68084-631">
        <manufacturer>American Health Packaging</manufacturer>
        <brand>Pioglitazone Hydrochloride</brand>
        <name>pioglitazone hydrochloride</name>
        <diagnosisCode>V341XXD</diagnosisCode>
        <diagnosisDescription>Passenger in 3-whl mv injured in clsn w hv veh nontraf, subs</diagnosisDescription>
        <qty>210</qty>
    </drug>
    <drug code="54569-5354">
        <manufacturer>A-S Medication Solutions LLC</manufacturer>
        <brand>Diazepam</brand>
        <name>diazepam</name>
        <diagnosisCode>S4912</diagnosisCode>
        <diagnosisDescription>Sltr-haris Type II physeal fracture of lower end of humerus</diagnosisDescription>
        <qty>191</qty>
    </drug>
    <drug code="21130-383">
        <manufacturer>Safeway, Inc.</manufacturer>
        <brand>Adult Cough Relief DM</brand>
        <name>Dextromethorphan HBr</name>
        <diagnosisCode>S7011</diagnosisCode>
        <diagnosisDescription>Contusion of right thigh</diagnosisDescription>
        <qty>191</qty>
    </drug>
    <drug code="0904-6183">
        <manufacturer>Major Pharmaceuticals</manufacturer>
        <brand>Guanfacine Hydrochloride</brand>
        <name>Guanfacine Hydrochloride</name>
        <diagnosisCode>S43213D</diagnosisCode>
        <diagnosisDescription>Anterior subluxation of unsp sternoclavicular joint, subs</diagnosisDescription>
        <qty>421</qty>
    </drug>
    <drug code="63629-4501">
        <manufacturer>Bryant Ranch Prepack</manufacturer>
        <brand>Phentermine Hydrochloride</brand>
        <name>Phentermine Hydrochloride</name>
        <diagnosisCode>S68127</diagnosisCode>
        <diagnosisDescription>Partial traumatic MCP amputation of left little finger</diagnosisDescription>
        <qty>480</qty>
    </drug>
  </clinic>
  <clinic id="3baa90fa-dc23-4eaf-926f-e4b7fcc30fb2">
    <address>
        <street>00387 Sloan Drive</street>
        <city>Kansas City</city>
        <region>Missouri</region>
        <country>United States</country>
    </address>
    <employee id="34b1b3e9-3fc9-4930-b2af-c70ad6a6dd83">
        <firstName>Rozina</firstName>
        <lastName>Spurryer</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="e9907735-48f5-4e14-ab42-5325859903ae">
        <firstName>Brandice</firstName>
        <lastName>Pryce</lastName>
        <empType>intern</empType>
    </employee>
    <employee id="1fef0fd9-f54b-4a28-8b87-df24f6c608ea">
        <firstName>Agna</firstName>
        <lastName>Harlow</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="0378-0087">
        <manufacturer>Mylan Pharmaceuticals Inc.</manufacturer>
        <brand>Maprotiline Hydrochloride</brand>
        <name>maprotiline hydrochloride</name>
        <diagnosisCode>T83590S</diagnosisCode>
        <diagnosisDescription>I/I react d/t implanted urn nstim dev, sequela</diagnosisDescription>
        <qty>85</qty>
    </drug>
    <drug code="0955-1021">
        <manufacturer>Winthrop U.S.</manufacturer>
        <brand>Docetaxel</brand>
        <name>Docetaxel</name>
        <diagnosisCode>S43006</diagnosisCode>
        <diagnosisDescription>Unspecified dislocation of unspecified shoulder joint</diagnosisDescription>
        <qty>198</qty>
    </drug>
    <drug code="65923-156">
        <manufacturer>United Exchange Corp.</manufacturer>
        <brand>Coralite Pain Relief</brand>
        <name>DL-Camphor, L-Menthol, Methylsalicylate</name>
        <diagnosisCode>T25511D</diagnosisCode>
        <diagnosisDescription>Corrosion of first degree of right ankle, subs encntr</diagnosisDescription>
        <qty>481</qty>
    </drug>
    <drug code="62034-015">
        <manufacturer>Blenheim Pharmacal, Inc.</manufacturer>
        <brand>clopidogrel bisulfate</brand>
        <name>clopidogrel bisulfate</name>
        <diagnosisCode>Q7211</diagnosisCode>
        <diagnosisDescription>Congen absence of right thigh and lower leg w foot present</diagnosisDescription>
        <qty>140</qty>
    </drug>
    <drug code="60760-182">
        <manufacturer>St Marys Medical Park Pharmacy</manufacturer>
        <brand>NIFEDIPINE</brand>
        <name>NIFEDIPINE</name>
        <diagnosisCode>T387X4</diagnosisCode>
        <diagnosisDescription>Poisoning by androgens and anabolic congeners, undetermined</diagnosisDescription>
        <qty>174</qty>
    </drug>
  </clinic>
  <clinic id="3afef871-5c97-4453-ada9-5d68e8f2e58d">
    <address>
        <street>07 Butterfield Alley</street>
        <city>Youngstown</city>
        <region>Ohio</region>
        <country>United States</country>
    </address>
    <employee id="5a7e6d7a-176a-4596-8032-486106bd377f">
        <firstName>Catriona</firstName>
        <lastName>Degoey</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="dec79287-17e5-4c8c-a3b5-290c8a225519">
        <firstName>Butch</firstName>
        <lastName>Fulford</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="dd709773-d825-4de9-87aa-60e5fe6fdc9c">
        <firstName>Cash</firstName>
        <lastName>Grandin</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="68788-9712">
        <manufacturer>Preferred Pharmaceuticals, Inc.</manufacturer>
        <brand>Losartan Potassium</brand>
        <name>Losartan Potassium</name>
        <diagnosisCode>S8609</diagnosisCode>
        <diagnosisDescription>Other specified injury of Achilles tendon</diagnosisDescription>
        <qty>448</qty>
    </drug>
    <drug code="63323-129">
        <manufacturer>APP Pharmaceuticals, LLC</manufacturer>
        <brand>Anastrozole</brand>
        <name>Anastrozole</name>
        <diagnosisCode>V2910XD</diagnosisCode>
        <diagnosisDescription>Mtrcy passenger injured in collision w unsp mv nontraf, subs</diagnosisDescription>
        <qty>313</qty>
    </drug>
    <drug code="54569-0826">
        <manufacturer>A-S Medication Solutions LLC</manufacturer>
        <brand>Fleet</brand>
        <name>sodium phosphate, dibasic and sodium phosphate, monobasic</name>
        <diagnosisCode>S40252</diagnosisCode>
        <diagnosisDescription>Superficial foreign body of left shoulder</diagnosisDescription>
        <qty>313</qty>
    </drug>
    <drug code="64117-219">
        <manufacturer>Natural Health Supply</manufacturer>
        <brand>SKIN ERUPTIONS</brand>
        <name>CHIMAPHILA UMBELLATA</name>
        <diagnosisCode>S3205</diagnosisCode>
        <diagnosisDescription>Fracture of fifth lumbar vertebra</diagnosisDescription>
        <qty>442</qty>
    </drug>
    <drug code="61722-042">
        <manufacturer>Kosan Kozmetik Sanayi ve Ticaret A.S.</manufacturer>
        <brand>flormar Concealer Sunscreen Broad Spectrum SPF 20 LC05 CAPPUCCINO</brand>
        <name>OCTINOXATE</name>
        <diagnosisCode>S85121A</diagnosisCode>
        <diagnosisDescription>Oth injury of unsp tibial artery, right leg, init encntr</diagnosisDescription>
        <qty>294</qty>
    </drug>
  </clinic>
  <clinic id="4ee91409-eb73-43aa-bf07-2f7b9da0bd73">
    <address>
        <street>76631 Garrison Circle</street>
        <city>Atlanta</city>
        <region>Georgia</region>
        <country>United States</country>
    </address>
    <employee id="4a6a0ac0-b266-4a63-973b-429949fb0ed6">
        <firstName>Thibaut</firstName>
        <lastName>Mazzei</lastName>
        <empType>contractor</empType>
    </employee>
    <employee id="2356551b-35a2-4a2c-afbe-9cea0721229e">
        <firstName>Bertram</firstName>
        <lastName>Hambrook</lastName>
        <empType>intern</empType>
    </employee>
    <employee id="2fea7fd2-fc32-4573-96ec-64c034f9b960">
        <firstName>Saundra</firstName>
        <lastName>Hakking</lastName>
        <empType>contractor</empType>
    </employee>
    <drug code="54973-0628">
        <manufacturer>Hyland's</manufacturer>
        <brand>VERATRUM ALBUM</brand>
        <name>VERATRUM ALBUM ROOT</name>
        <diagnosisCode>V320XXA</diagnosisCode>
        <diagnosisDescription>Driver of 3-whl mv inj in clsn w 2/3-whl mv nontraf, init</diagnosisDescription>
        <qty>51</qty>
    </drug>
    <drug code="61096-0032">
        <manufacturer>Eight and Company</manufacturer>
        <brand>Sprayology Arnica Power 3</brand>
        <name>Arnica montana</name>
        <diagnosisCode>S42141B</diagnosisCode>
        <diagnosisDescription>Disp fx of glenoid cav of scapula, r shldr, init for opn fx</diagnosisDescription>
        <qty>465</qty>
    </drug>
    <drug code="11523-7272">
        <manufacturer>MSD Consumer Care, Inc.</manufacturer>
        <brand>Coppertone UltraGuard</brand>
        <name>Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone</name>
        <diagnosisCode>S71141</diagnosisCode>
        <diagnosisDescription>Puncture wound with foreign body, right thigh</diagnosisDescription>
        <qty>129</qty>
    </drug>
    <drug code="16590-033">
        <manufacturer>Stat Rx USA</manufacturer>
        <brand>BETAMETHASONE CLOTRIMAZOLE</brand>
        <name>BETAMETHASONE CLOTRIMAZOLE</name>
        <diagnosisCode>T83113A</diagnosisCode>
        <diagnosisDescription>Breakdown (mechanical) of other urinary stents, init</diagnosisDescription>
        <qty>492</qty>
    </drug>
    <drug code="53208-551">
        <manufacturer>LG Household and Healthcare, Inc.</manufacturer>
        <brand>OH Age recovery Tri Shield pact 10</brand>
        <name>TITANIUM DIOXIDE, OCTINOXATE</name>
        <diagnosisCode>S42156A</diagnosisCode>
        <diagnosisDescription>Nondisp fx of neck of scapula, unsp shoulder, init</diagnosisDescription>
        <qty>112</qty>
    </drug>
  </clinic>
  <clinic id="53099d06-064f-4b44-b02c-54bd64cc3024">
    <address>
        <street>85 Farwell Drive</street>
        <city>Linton</city>
        <region>England</region>
        <country>United Kingdom</country>
    </address>
    <employee id="32dc81c8-97e8-4fe7-a523-893e3ba65d02">
        <firstName>Frederik</firstName>
        <lastName>Mosdell</lastName>
        <empType>contractor</empType>
    </employee>
    <employee id="c7cb7bd1-aa8e-474f-a4df-007508d24e84">
        <firstName>Aveline</firstName>
        <lastName>Wainer</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="b5f36801-a88c-484c-a59c-84afdb03f8d1">
        <firstName>Ted</firstName>
        <lastName>Dungey</lastName>
        <empType>intern</empType>
    </employee>
    <drug code="0615-7507">
        <manufacturer>NCS HealthCare of KY, Inc dba Vangard Labs</manufacturer>
        <brand>Risperidone</brand>
        <name>risperidone</name>
        <diagnosisCode>S72001H</diagnosisCode>
        <diagnosisDescription>Fx unsp prt of nk of r femr, 7thH</diagnosisDescription>
        <qty>30</qty>
    </drug>
    <drug code="61919-012">
        <manufacturer>Direct Rx</manufacturer>
        <brand>AMITRIPTYLINE HYDROCHLORIDE</brand>
        <name>AMITRIPTYLINE HYDROCHLORIDE</name>
        <diagnosisCode>L859</diagnosisCode>
        <diagnosisDescription>Epidermal thickening, unspecified</diagnosisDescription>
        <qty>298</qty>
    </drug>
    <drug code="60681-6301">
        <manufacturer>Sanum Kehlbeck GmbH &amp; Co. KG</manufacturer>
        <brand>Pleo Sanuvis</brand>
        <name>lactic acid, l-</name>
        <diagnosisCode>S15211A</diagnosisCode>
        <diagnosisDescription>Minor laceration of right external jugular vein, init encntr</diagnosisDescription>
        <qty>327</qty>
    </drug>
     <drug code="32909-755">
        <manufacturer>E-Z-EM Canada Inc</manufacturer>
        <brand>Readi-Cat2 Vanilla Smoothie</brand>
        <name>Barium Sulfate</name>
        <diagnosisCode>M6146</diagnosisCode>
        <diagnosisDescription>Other calcification of muscle, lower leg</diagnosisDescription>
        <qty>403</qty>
    </drug>
    <drug code="54868-6145">
        <manufacturer>Physicians Total Care, Inc.</manufacturer>
        <brand>Rivastigmine Tartrate</brand>
        <name>rivastigmine tartrate</name>
        <diagnosisCode>T25421S</diagnosisCode>
        <diagnosisDescription>Corrosion of unspecified degree of right foot, sequela</diagnosisDescription>
        <qty>443</qty>
    </drug>
  </clinic>
  <clinic id="98576a89-1f2c-4ff4-a392-77cce24ae509">
    <address>
        <street>49811 Sundown Trail</street>
        <city>Dallas</city>
        <region>Texas</region>
        <country>United States</country>
    </address>
    <employee id="eaf847d0-eb4f-4e26-8603-9de59b1679ea">
        <firstName>Lulita</firstName>
        <lastName>Goundsy</lastName>
        <empType>contractor</empType>
    </employee>
    <employee id="c38357e6-2bd4-49c1-9790-8af96998c8ce">
        <firstName>Davidde</firstName>
        <lastName>Gregoriou</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="37fb8dd4-a023-4c05-a48a-9394039c249b">
        <firstName>Carroll</firstName>
        <lastName>Kennefick</lastName>
        <empType>full-time</empType>
    </employee>
    <drug code="54868-2877">
        <manufacturer>Physicians Total Care, Inc.</manufacturer>
        <brand>Vitamin A and Vitamin D</brand>
        <name>PETROLATUM</name>
        <diagnosisCode>H18621</diagnosisCode>
        <diagnosisDescription>Keratoconus, unstable, right eye</diagnosisDescription>
        <qty>201</qty>
    </drug>
    <drug code="62935-452">
        <manufacturer>TOLMAR Pharmaceuticals, Inc.</manufacturer>
        <brand>ELIGARD</brand>
        <name>Leuprolide Acetate</name>
        <diagnosisCode>S00269S</diagnosisCode>
        <diagnosisDescription>Insect bite of unsp eyelid and periocular area, sequela</diagnosisDescription>
        <qty>28</qty>
    </drug>
    <drug code="48951-8034">
        <manufacturer>Uriel Pharmacy Inc.</manufacturer>
        <brand>Plantago Primula</brand>
        <name>Plantago Primula</name>
        <diagnosisCode>O411025</diagnosisCode>
        <diagnosisDescription>Infct of amniotic sac and membrns, unsp, second tri, fetus 5</diagnosisDescription>
        <qty>79</qty>
    </drug>
    <drug code="63824-016">
        <manufacturer>Reckitt Benckiser LLC</manufacturer>
        <brand>Mucinex Fast-Max</brand>
        <name>Acetaminophen, Guaifenesin, and Phenylephrine Hydrochloride</name>
        <diagnosisCode>S90931S</diagnosisCode>
        <diagnosisDescription>Unspecified superficial injury of right great toe, sequela</diagnosisDescription>
        <qty>496</qty>
    </drug>
    <drug code="49449-100">
        <manufacturer>Theraceutix, LLC</manufacturer>
        <brand>TCX Skincare</brand>
        <name>Colloidal Oatmeal</name>
        <diagnosisCode>S61210</diagnosisCode>
        <diagnosisDescription>Laceration w/o foreign body of r idx fngr w/o damage to nail</diagnosisDescription>
        <qty>9</qty>
    </drug>
  </clinic>
  <clinic id="c4c6ad57-cc08-443f-9b7b-54a31f222d97">
    <address>
        <street>83 Logan Alley</street>
        <city>Caen</city>
        <region>Basse-Normandie</region>
        <country>France</country>
    </address>
    <employee id="63a2b7ff-1cb4-45dc-9563-93d7c1e55c04">
        <firstName>Wainwright</firstName>
        <lastName>Beeck</lastName>
        <empType>contractor</empType>
    </employee>
    <employee id="4e89d3dc-f348-446d-8f74-62b70d8845bc">
        <firstName>Wolf</firstName>
        <lastName>Catlette</lastName>
        <empType>full-time</empType>
    </employee>
    <employee id="d0eb38c9-ebed-4fdc-831e-6ad0a35107cb">
        <firstName>Fran</firstName>
        <lastName>Marrion</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="36800-234">
        <manufacturer>Topco Associates LLC</manufacturer>
        <brand>Topcare Cold Head Congestion Severe</brand>
        <name>Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl</name>
        <diagnosisCode>T2065XD</diagnosisCode>
        <diagnosisDescription>Corrosion of second degree of scalp, subsequent encounter</diagnosisDescription>
        <qty>401</qty>
    </drug>
    <drug code="24794-105">
        <manufacturer>Crosstex International Inc.</manufacturer>
        <brand>Zap APF</brand>
        <name>Sodium Fluoride</name>
        <diagnosisCode>T465X1S</diagnosisCode>
        <diagnosisDescription>Poisoning by oth antihypertn drugs, accidental, sequela</diagnosisDescription>
        <qty>34</qty>
    </drug>
    <drug code="57664-117">
        <manufacturer>Caraco Pharmaceutical Laboratories, Ltd.</manufacturer>
        <brand>VERAPAMIL HYDROCHLORIDE</brand>
        <name>VERAPAMIL HYDROCHLORIDE</name>
        <diagnosisCode>S60949A</diagnosisCode>
        <diagnosisDescription>Unsp superficial injury of unspecified finger, init encntr</diagnosisDescription>
        <qty>332</qty>
    </drug>
    <drug code="41250-700">
        <manufacturer>Meijer Distribution Inc</manufacturer>
        <brand>nicotine</brand>
        <name>Nicotine polacrilex</name>
        <diagnosisCode>S51841S</diagnosisCode>
        <diagnosisDescription>Puncture wound with foreign body of right forearm, sequela</diagnosisDescription>
        <qty>470</qty>
    </drug>
    <drug code="51346-051">
        <manufacturer>NATURE REPUBLIC CO., LTD.</manufacturer>
        <brand>BLEMISH LAB BYE PORE BB</brand>
        <name>TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE</name>
        <diagnosisCode>S12150K</diagnosisCode>
        <diagnosisDescription>Oth traum displ spondylolysis of 2nd cervcal vert, 7thK</diagnosisDescription>
        <qty>139</qty>
    </drug>
  </clinic>
  <clinic id="32f2022f-0c5a-46c1-a226-5afa86e14a20">
    <address>
        <street>35749 Petterle Parkway</street>
        <city>Clichy</city>
        <region>Île-de-France</region>
        <country>France</country>
    </address>
    <employee id="92b91ab5-e272-4283-aa27-c17372189a9f">
        <firstName>Meris</firstName>
        <lastName>Coultard</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="50c846dd-b4e7-45af-ac86-9ad2b483a024">
        <firstName>Horacio</firstName>
        <lastName>Clinch</lastName>
        <empType>intern</empType>
    </employee>
    <employee id="8bf23a9c-3f7d-4503-81fe-d7267fd1fe34">
        <firstName>Verene</firstName>
        <lastName>Carrabot</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="62856-705">
        <manufacturer>Eisai Inc.</manufacturer>
        <brand>Salagen</brand>
        <name>pilocarpine hyrochloride</name>
        <diagnosisCode>P5699</diagnosisCode>
        <diagnosisDescription>Hydrops fetalis due to other hemolytic disease</diagnosisDescription>
        <qty>459</qty>
    </drug>
    <drug code="68151-0703">
        <manufacturer>Carilion Materials Management</manufacturer>
        <brand>Acetaminophen and Diphenhydramine HCl</brand>
        <name>Acetaminophen and Diphenhydramine HCl</name>
        <diagnosisCode>M84375K</diagnosisCode>
        <diagnosisDescription>Stress fracture, left foot, subs for fx w nonunion</diagnosisDescription>
        <qty>73</qty>
    </drug>
    <drug code="59762-3304">
        <manufacturer>Greenstone LLC</manufacturer>
        <brand>NITROGLYCERIN</brand>
        <name>nitroglycerin</name>
        <diagnosisCode>S46009</diagnosisCode>
        <diagnosisDescription>Unsp injury of musc/tend the rotator cuff of unsp shoulder</diagnosisDescription>
        <qty>194</qty>
    </drug>
    <drug code="50241-143">
        <manufacturer>Morgan Gallacher, Inc. DBA Custom Chemical Formulators, Inc.</manufacturer>
        <brand>PROBLEND Antibacterial Liquid Cleanser</brand>
        <name>Parachlorometaxylenol</name>
        <diagnosisCode>S45192</diagnosisCode>
        <diagnosisDescription>Other specified injury of brachial artery, left side</diagnosisDescription>
        <qty>12</qty>
    </drug>
    <drug code="52564-308">
        <manufacturer>Mueller Sports Medicine, Inc.</manufacturer>
        <brand>Hot Stuff Cream</brand>
        <name>Capsaicin</name>
        <diagnosisCode>S63</diagnosisCode>
        <diagnosisDescription>Dislocation and sprain of joints and ligaments at wrs/hnd lv</diagnosisDescription>
        <qty>408</qty>
    </drug>
  </clinic>
  <clinic id="d3389b97-e38b-4233-91ea-856ffa5f9dfa">
    <address>
        <street>9 Mockingbird Junction</street>
        <city>Las Vegas</city>
        <region>Nevada</region>
        <country>United States</country>
    </address>
    <employee id="81cb939c-9ca5-41b2-9e3b-9be69147e00e">
        <firstName>Jesse</firstName>
        <lastName>Shand</lastName>
        <empType>intern</empType>
    </employee>
    <employee id="e07e4084-11fa-4cb6-8ba5-559c338265e3">
        <firstName>Carmella</firstName>
        <lastName>Dani</lastName>
        <empType>full-time</empType>
    </employee>
    <employee id="06ec0ed8-95fc-43e5-87db-c100e2414af0">
        <firstName>Kristina</firstName>
        <lastName>McBean</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="0074-1564">
        <manufacturer>AbbVie Inc.</manufacturer>
        <brand>Depacon</brand>
        <name>Valproate Sodium</name>
        <diagnosisCode>V870XXD</diagnosisCode>
        <diagnosisDescription>Person injured in clsn betw car and 2/3-whl pwr veh, subs</diagnosisDescription>
        <qty>81</qty>
    </drug>
    <drug code="59746-177">
        <manufacturer>JUBILANT CADISTA PHARMACEUTICALS, INC.</manufacturer>
        <brand>cyclobenzaprine hydrochloride</brand>
        <name>cyclobenzaprine hydrochloride</name>
        <diagnosisCode>I8322</diagnosisCode>
        <diagnosisDescription>Varicose veins of l low extrem w ulc and inflammation</diagnosisDescription>
        <qty>93</qty>
    </drug>
    <drug code="53746-179">
        <manufacturer>Amneal Pharmaceuticals</manufacturer>
        <brand>Metformin Hydrochloride</brand>
        <name>Metformin Hydrochloride</name>
        <diagnosisCode>M1904</diagnosisCode>
        <diagnosisDescription>Primary osteoarthritis, hand</diagnosisDescription>
        <qty>487</qty>
    </drug>
     <drug code="55910-200">
        <manufacturer>Dolgencorp, LLC</manufacturer>
        <brand>dg health pain relief</brand>
        <name>Acetaminophen</name>
        <diagnosisCode>T22721D</diagnosisCode>
        <diagnosisDescription>Corrosion of third degree of right elbow, subs encntr</diagnosisDescription>
        <qty>80</qty>
    </drug>
    <drug code="0113-0154">
        <manufacturer>L Perrigo Company</manufacturer>
        <brand>good sense athletes foot</brand>
        <name>tolnaftate</name>
        <diagnosisCode>M24139</diagnosisCode>
        <diagnosisDescription>Other articular cartilage disorders, unspecified wrist</diagnosisDescription>
        <qty>309</qty>
    </drug>
  </clinic>
  <clinic id="ad3da69d-1681-47a0-9f1e-f3a06fa42390">
    <address>
        <street>5043 Larry Parkway</street>
        <city>Dallas</city>
        <region>Texas</region>
        <country>United States</country>
    </address>
    <employee id="e119867c-404a-4d66-b30a-95b6715df64a">
        <firstName>Kristien</firstName>
        <lastName>Le Batteur</lastName>
        <empType>part-time</empType>
    </employee>
    <employee id="2c37678f-51de-4f0d-961e-ab0e63d5790a">
        <firstName>Carmine</firstName>
        <lastName>Deakan</lastName>
        <empType>intern</empType>
    </employee>
    <employee id="f6f19892-a9da-4fdf-a723-b4b6bc78aca4">
        <firstName>Darrel</firstName>
        <lastName>MacDougal</lastName>
        <empType>contractor</empType>
    </employee>
    <drug code="21695-653">
        <manufacturer>Rebel Distributors Corp</manufacturer>
        <brand>Haloperidol</brand>
        <name>Haloperidol</name>
        <diagnosisCode>I512</diagnosisCode>
        <diagnosisDescription>Rupture of papillary muscle, not elsewhere classified</diagnosisDescription>
        <qty>414</qty>
    </drug>
    <drug code="49884-984">
        <manufacturer>Par Pharmaceutical Inc.</manufacturer>
        <brand>Nateglinide</brand>
        <name>Nateglinide</name>
        <diagnosisCode>J0181</diagnosisCode>
        <diagnosisDescription>Other acute recurrent sinusitis</diagnosisDescription>
        <qty>201</qty>
    </drug>
    <drug code="53329-933">
        <manufacturer>Medline Industries, Inc.</manufacturer>
        <brand>Obstetrical Antiseptic</brand>
        <name>Benzalkonium Chloride</name>
        <diagnosisCode>H59361</diagnosisCode>
        <diagnosisDescription>Postproc seroma of right eye and adnexa fol other procedure</diagnosisDescription>
        <qty>482</qty>
    </drug>
    <drug code="16590-126">
        <manufacturer>STAT RX USA LLC</manufacturer>
        <brand>IBUPROFEN</brand>
        <name>IBUPROFEN</name>
        <diagnosisCode>S62331</diagnosisCode>
        <diagnosisDescription>Disp fx of neck of second metacarpal bone, left hand</diagnosisDescription>
        <qty>168</qty>
    </drug>
    <drug code="63868-251">
        <manufacturer>Chain Drug Marketing Association</manufacturer>
        <brand>Awaken by Quality Choice Anti-Wrinkle and Firming Moisturizer Day Broad Spectrum SPF18 Sunscreen</brand>
        <name>Avobenzone, Octisalate and Octocrylene</name>
        <diagnosisCode>S65590</diagnosisCode>
        <diagnosisDescription>Other specified injury of blood vessel of right index finger</diagnosisDescription>
        <qty>81</qty>
    </drug>
  </clinic>
  <clinic id="2e9be843-21c8-4824-b093-76be483c6606">
    <address>
        <street>7 Briar Crest Terrace</street>
        <city>Bremen</city>
        <region>Bremen</region>
        <country>Germany</country>
    </address>
    <employee id="75b6c212-42bb-4778-b9be-1ee14789b9a3">
        <firstName>Dougie</firstName>
        <lastName>Ziehm</lastName>
        <empType>full-time</empType>
    </employee>
    <employee id="62faa73e-b710-442a-b5aa-3b9288a99ca3">
        <firstName>Gayler</firstName>
        <lastName>Roper</lastName>
        <empType>intern</empType>
    </employee>
    <employee id="485a2796-ba9a-42eb-b46b-73467a93eca8">
        <firstName>James</firstName>
        <lastName>Barringer</lastName>
        <empType>part-time</empType>
    </employee>
    <drug code="49967-084">
        <manufacturer>L'Oreal USA Products Inc</manufacturer>
        <brand>La Roche Posay</brand>
        <name>Avobenzone Homosalate Octisalate Octocrylene Oxybenzone</name>
        <diagnosisCode>M47819</diagnosisCode>
        <diagnosisDescription>Spondylosis without myelopathy or radiculopathy, site unsp</diagnosisDescription>
        <qty>342</qty>
    </drug>
    <drug code="52533-048">
        <manufacturer>Cantrell Drug Company</manufacturer>
        <brand>Oxytocin</brand>
        <name>Oxytocin</name>
        <diagnosisCode>L0501</diagnosisCode>
        <diagnosisDescription>Pilonidal cyst with abscess</diagnosisDescription>
        <qty>314</qty>
    </drug>
    <drug code="0268-6643">
        <manufacturer>ALK-Abello, Inc.</manufacturer>
        <brand>QUERCUS VIRGINIANA POLLEN</brand>
        <name>Virginia Live Oak</name>
        <diagnosisCode>S52246R</diagnosisCode>
        <diagnosisDescription>Nondisp spiral fx shaft of ulna, unsp arm, 7thR</diagnosisDescription>
        <qty>299</qty>
    </drug>
    <drug code="61481-0037">
        <manufacturer>KINeSYS Pharmaceutical Inc.</manufacturer>
        <brand>KINeSYS EarthKind SPF 30 Sunscreen</brand>
        <name>ZINC OXIDE</name>
        <diagnosisCode>S71041</diagnosisCode>