<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE businesscards 
[
    <!ELEMENT businesscards (individual+)>
    <!ELEMENT individual (personName , contact, mailAddress)>
    <!ELEMENT personName  (#PCDATA)>
    <!ELEMENT contact (#PCDATA)>
    <!ATTLIST contact type (home | work | mobile) #IMPLIED>
    <!ELEMENT mailAddress (#PCDATA)>
]>
<businesscards>
    <individual>
        <personName>Rorie Demanche</personName>
        <contact type="home">+1 (710) 153-4949</contact>
        <contact type="work">+1 (503) 319-3558</contact>
        <contact type="mobile">+1 (182) 748-1667</contact>
        <mailAddress>rdemanche0@foxnews.com</mailAddress>
    </individual>
    <individual>
        <personName>Kelcey Surman</personName>
        <contact type="home">+1 (249) 926-7376</contact>
        <contact type="work">+1 (208) 363-6588</contact>
        <contact type="mobile">+1 (982) 536-6860</contact>
        <mailAddress>ksurman1@usnews.com</mailAddress>
    </individual>
    <individual>
        <personName>Simon Heddan</personName>
        <contact type="home">+1 (687) 808-4290</contact>
        <contact type="work">+1 (604) 815-7810</contact>
        <contact type="mobile">+1 (924) 174-3271</contact>
        <mailAddress>sheddan2@alexa.com</mailAddress>
    </individual>
    <individual>
        <personName>Chan Supple</personName>
        <contact type="home">+1 (577) 165-2495</contact>
        <contact type="work">+1 (547) 934-7337</contact>
        <contact type="mobile">+1 (367) 667-0747</contact>
        <mailAddress>csupple3@123-reg.co.uk</mailAddress>
    </individual>
</businesscards>

