<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE menuInfo [
  <!ELEMENT menuInfo (title, summary, effectiveDate, menu+ )>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT summary (#PCDATA)>
  <!ELEMENT effectiveDate (#PCDATA)>
  <!ELEMENT menu (category, menuItem+ )>
  <!ELEMENT category (#PCDATA)>
  <!ELEMENT menuItem (name+,description,price,indicator* )>
  <!ELEMENT name (#PCDATA)>
  <!ATTLIST name type (original|old) #REQUIRED>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT indicator (#PCDATA)>
  <!ATTLIST indicator category CDATA #REQUIRED>
]>
<menuInfo>
  <title>Chester's Breakfast Menu</title>
  <summary>
    <![CDATA[
    If you've been craving an authentic homestyle country breakfast,
    look no further than Chester's!  We've got your breakfast favorites served
    up just the way you like them!!
    ]]>
  </summary>
  <effectiveDate>03/12/2016</effectiveDate>
  <menu>
    <category>Traditional Favorites</category>
    <menuItem>
      <name type="original">Rise n' Shine</name>
      <name type="old">Shine</name>
      <description>
        <![CDATA[
        Two Eggs* cooked to order with Grits, Gravy and Homemade Buttermilk
        Biscuits along with real Butter and the best fresh jam
        available. Served with your choice of Fresh Fruit or Hashbrown Casserole
        and Smoked Sausage Patties, Turkey Sausage Patties or Thick-Sliced Bacon.
        ]]>
      </description>
      <price>7.95</price>
    </menuItem>
    <menuItem>
      <name type="original">Fresh Mornin' Sampler </name>
      <name type="old">Mornin' Sampler </name>
      <description>
        <![CDATA[
        Low-Fat Vanilla Yogurt and Seasonal Fruit topped with our Honey Granola
        mix of Almonds and Dried Fruit. Served with a Wild Maine Blueberry Muffin
        or an Apple Bran Muffin.
        ]]>
      </description>
      <price>6.95</price>
      <indicator category="heart healthy">&#9829;</indicator>
      <indicator category="low-sodium">&#9830;</indicator>
      <indicator category="vegan">&#9824;</indicator>
    </menuItem>
  </menu>
  <menu>
    <category>Lite and Quick</category>
    <menuItem>
      <name type="original">Oatmeal Breakfast</name>
      <description>
        <![CDATA[
        Our Oatmeal is served warm with your choice of Fried Apples, Pecans, Raisins,
        Fresh Sliced Bananas or 100% Pure Natural Syrup. Also, served with your
        choice of Apple Bran Muffin or Wild Maine Blueberry Muffin. Available
        all day.
        ]]>
      </description>
      <price>6.95</price>
      <indicator category="heart healthy">&#9829;</indicator>
      <indicator category="low-sodium">&#9830;</indicator>
      <indicator category="vegan">&#9824;</indicator>
    </menuItem>
    <menuItem>
      <name type="original">Chester's Meat Platter</name>
      <name type="old">Chester Platter </name>
      <description>
        <![CDATA[
        Country Ham, Pork Chops or Steak* grilled to order, Three Eggs* cooked
        to order served with Cottage Cheese, Smoked Sausage Patties, Turkey
        Sausage Patties or Thick-Sliced Bacon.
        ]]>
      </description>
      <price>12.95</price>
      <indicator category="low-carb">&#9832;</indicator>
    </menuItem>
  </menu>
</menuInfo>
<!-- Name: Wenhao Fang; ID: n01555914 -->